# Generated by Django 4.2.23 on 2025-07-29 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_newslettersubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactrequest',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='newslettersubscription',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254),
        ),
    ]
