# Generated by Django 4.2.23 on 2025-06-11 11:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('img', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='img',
            name='caption',
            field=models.CharField(default='test', max_length=1000, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='img',
            name='favourites',
            field=models.ManyToManyField(blank=True, default=None, related_name='favourite', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='img',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10),
        ),
    ]
