# Generated by Django 4.2.23 on 2025-06-11 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('img', '0002_img_caption_img_favourites_img_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='img',
            name='slug',
            field=models.SlugField(default='test', max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
