# Generated by Django 4.2.23 on 2025-06-11 17:58

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('img', '0003_img_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img',
            name='image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
