# Generated by Django 4.2.23 on 2025-08-09 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('img', '0005_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img',
            name='caption',
            field=models.TextField(max_length=1000, unique=True),
        ),
    ]
